### ISSUE TITLE
大佬您好，现在有大佬做了ax200的驱动，可以上网

### ISSUE THREAD

**Issue by Sulisong** [CyrilTaylor/Legion-Y9000X-Hackintosh#1]
我现在在用，您可以看看 https://github.com/zxystd/itlwm

**Comment by CyrilTaylor** [comment]
嗯嗯，这个我也在远景论坛看到了，但是我自己的AX200已经卖掉了，所以没办法测试。
而且Intel的WiFi暂时还不是很好用，比如SSID和密码都是驱动写死的，当你需要连不通的WiFi的时候就很不方便

**Comment by Sulisong** [comment]
不是的哦，现在有客户端了，和自带的WiFi客户端一样，在用



------------------ 原始邮件 ------------------
发件人: Cyril Taylor <notifications@github.com&gt;
发送时间: 2020年7月5日 12:40
收件人: CyrilTaylor/Legion-Y9000X-Hackintosh <Legion-Y9000X-Hackintosh@noreply.github.com&gt;
抄送: 苏lisong <1183148426@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[CyrilTaylor/Legion-Y9000X-Hackintosh] 大佬您好，现在有大佬做了ax200的驱动，可以上网 (#1)





 
嗯嗯，这个我也在远景论坛看到了，但是我自己的AX200已经卖掉了，所以没办法测试。
 而且Intel的WiFi暂时还不是很好用，比如SSID和密码都是驱动写死的，当你需要连不通的WiFi的时候就很不方便

**Comment by CyrilTaylor** [comment]
我的已经卖了，所以我的仓库不会加入这个的支持，加入有需要，可以拉仓库自己改

但是我的仓库的EFI目前还没发布，很多问题都没有弄好，我暂时只是开仓库备份下配置，所以请不要用于实际引导哦，当仓库发布可用的版本的时候，在Release页会有EFI包的

**Comment by Sulisong** [comment]
好的，谢谢回复哈





------------------ 原始邮件 ------------------
发件人: Cyril Taylor <notifications@github.com&gt;
发送时间: 2020年7月5日 12:46
收件人: CyrilTaylor/Legion-Y9000X-Hackintosh <Legion-Y9000X-Hackintosh@noreply.github.com&gt;
抄送: 苏lisong <1183148426@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[CyrilTaylor/Legion-Y9000X-Hackintosh] 大佬您好，现在有大佬做了ax200的驱动，可以上网 (#1)





 
我的已经卖了，所以我的仓库不会加入这个的支持，加入有需要，可以拉仓库自己改
 
但是我的仓库的EFI目前还没发布，很多问题都没有弄好，我暂时只是开仓库备份下配置，所以请不要用于实际引导哦，当仓库发布可用的版本的时候，在Release页会有EFI包的

**Comment by CyrilTaylor** [comment]
不客气
