### ISSUE TITLE
请问这个efi是基于那一个bios版本开发的？

### ISSUE THREAD

**Issue by wqrqwerqrw** [CyrilTaylor/Legion-Y9000X-Hackintosh#2]
我现在用的是基于[WangRicky](https://github.com/WangRicky/Y9000X-HACKINTOSH)版本稍加修改的EFI

BIOS版本21的时候*开/合盖唤醒/休眠/自动关闭内屏*是**无效**的
但是降级到19就有效了，同时貌似20版也是有效的
所以我感觉这个功能和BIOS版本是有关的

**Comment by CyrilTaylor** [comment]
[WangRicky](https://github.com/WangRicky/Y9000X-HACKINTOSH)的我试过了，21版本的也是可以合盖休眠的，我目前是基于21版本的固件测试的，不过我的合盖休眠也是有点问题，直接点sleep是可以睡下去的，但是合盖不会触发休眠，所以我还在试合盖的补丁。
