### ISSUE TITLE
问下1080P要删除这个吗

### ISSUE THREAD

**Issue by zorroye** [CyrilTaylor/Legion-Y9000X-Hackintosh#3]
这个选项要删除吗？ 
OpenCore Configurator -> DeviceProperties -> PciRoot(0x0)/Pci(0x2,0x0)

**Comment by CyrilTaylor** [comment]
不需要，只需要把`dpcd-max-link-rate`为`0A000000`即可
假如在意开机苹果logo大小的，还需要修改`UIScale`为`01`

这个也适用于其他efi
