### ISSUE TITLE
温度检测正常吗？

### ISSUE THREAD

**Issue by zorroye** [CyrilTaylor/Legion-Y9000X-Hackintosh#4]
我这边只能检测到硬盘温度，其他温度全部显示不出来。。。
相关kext我都放了还是没有，问下楼主有没有这个情况？

**Comment by CyrilTaylor** [comment]
要显示CPU温度，需要安装[Intel Power Gadget](https://software.intel.com/en-us/articles/intel-power-gadget)，具体说明请参考[CPU frequency support](https://bjango.com/help/istatmenus6/frequency/)

![image](https://user-images.githubusercontent.com/12631466/94572995-3a3e8500-02a4-11eb-9039-c0171efc3435.png)
