### ISSUE TITLE
声音可以外方吗？

### ISSUE THREAD

**Issue by carsonlius** [CyrilTaylor/Legion-Y9000X-Hackintosh#5]
大佬  声音可以外放吗？

**Comment by CyrilTaylor** [comment]
外放目测99.99%没戏了，还是老老实实买个蓝牙音箱吧

**Comment by M69W** [comment]
> 外放目测99.99%没戏了，还是老老实实买个蓝牙音箱吧

外接可以吧，3.5mm耳机，type-c耳机之类的

**Comment by cuteluo1983** [comment]
> > 外放目测99.99%没戏了，还是老老实实买个蓝牙音箱吧
> 
> 外接可以吧，3.5mm耳机，type-c耳机之类的

外接可以，配个type-c解码+3.5mm耳机，棒棒哒

**Comment by CyrilTaylor** [comment]
蓝牙音箱无缠线困扰。总结就是除了内置的外放，其他的音频方式均可用

**Comment by M69W** [comment]
> > > 外放目测99.99%没戏了，还是老老实实买个蓝牙音箱吧
> > 
> > 
> > 外接可以吧，3.5mm耳机，type-c耳机之类的
> 
> 外接可以，配个type-c解码+3.5mm耳机，棒棒哒

小新Pro13 也类似，内置麦克风罢工，外接耳机可以用麦克风
